language: php

php:
  - 5.5.9
node_js:
  - 4.6.0

sudo: required

before_script:
  - cp .env.example .env
  - composer install --no-interaction
  - npm install -g yarn
  - npm install -g n
  - n stable
  - node -v
  - yarn
  - php artisan key:generate
  - gulp


script:
  - vendor/bin/phpunit
