sudo: required

language: php

php:
  - 5.6.4

before_install:
  - sudo rm -rf ~/.nvm
  - curl -sL "https://deb.nodesource.com/setup_4.x" | sudo -E bash -
  - sudo apt-get install -y nodejs

before_script:
  - cp .env.example .env
  - composer install --no-interaction
  - sudo npm install -g yarn
  - yarn
  - php artisan key:generate
  - gulp


script:
  - vendor/bin/phpunit
