language: php

php:
  - 5.5.9

before_script:
  - cp .env.example .env
  - composer install --no-interaction
  - npm install && npm install --dev
  - php artisan key:generate
  - gulp

script:
  - vendor/bin/phpunit
